// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
	"time"
)

type Geolocation struct {
	Ip        string
	Latitude  float64
	Longitude float64
	City      string
	Country   string
	Timezone  string
}

type Observation struct {
	ID                int64
	Latitude          float64
	Longitude         float64
	Timezone          string
	TempC             float64
	TempF             float64
	RelativeHumidity  float64
	Rain              float64
	Snowfall          float64
	WeatherCode       string
	DrawingDataUri    sql.NullString
	DrawingSizeBytes  sql.NullInt64
	TimeUtc           time.Time
	TimeLocal         time.Time
	TimeDrawingSubmit sql.NullTime
}
