// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
	"time"
)

type Geolocation struct {
	Ip        string
	Latitude  float64
	Longitude float64
}

type Observation struct {
	ID                 int64
	TimeUtc            time.Time
	TimeLocal          time.Time
	Timezone           string
	Latitude           float64
	Longitude          float64
	Temperature2m      float64
	RelativeHumidity2m float64
	Rain               float64
	Showers            float64
	Snowfall           float64
	DrawingDataUri     sql.NullString
	DrawingSizeBytes   sql.NullInt64
}
